### ISSUE TITLE
Delete a single message

### ISSUE THREAD

**Issue by alallo** [DigitalMolecules/vscode-servicebus-explorer#37]
Hi there

I can see from the git history that a one point there was an option to delete a single message from the messages view. That option was then removed and replaced with the "PurgeMessages" functionality. What was the reason behind this change?

It happened a lot of time that I had to delete single messages so this feature is quite useful.

Thanks
Alessandro

**Comment by andreujuanc** [comment]
Hi @alallo 

Indeed we removed it because we were changing the client implementation. 
The ServiceBus library we were using has been updated several times for which we have started to port to it. Before that, we were using the REST API.

@konradmainzer  already started to work on it, so you may expect this feature to be released very soon.

**Comment by alallo** [comment]
Hi Juan

thanks for the quick reply. That's great news!

**Comment by andreujuanc** [comment]
Reopening for tracking.

**Comment by andreujuanc** [comment]
@alallo Closing this since it's been released to the store. Please let us know if this covers your use case.
