### ISSUE TITLE
Feature request: Support opening gzipped messages

### ISSUE THREAD

**Issue by span** [DigitalMolecules/vscode-servicebus-explorer#44]
While it is great to be able to open plain text messages I've run into scenarios where there are lots of zipping going on. It would be great to be able to open gzipped messages.

I have some basic zipping/unzipping code that I am using locally on my machine that I am working with at the moment. I would love to contribute the code to the plugin but I am not sure on how to design this GUI/UX-wise.

A few thoughts on how it can be implemented (in no reasonable order):
1. Display a "unzip" button next to the "open" button for messages that are zipped
2. Suggest to "unzip" if a user opens a zipped message
3. Add "unzip and view" action that can unzip a message in a subscription

The next step would of course be to send zipped messages as well. Some thoughts?

**Comment by andreujuanc** [comment]
Hi, 
Indeed it'd be great to have it. We didn't because we didnt dealt with gzipped messages.

Well, we could see first if the message is zipped, if so then we proceed to open it seamlessly. For advance usage, we could provide two other commands to open raw (plain text) and unzipped. This could be implemented as a dropdown action button on the open mesasge button.

It shouldnt be any friction for the user to open either type of message. 

We accept PRs if you need this now, otherwise it might take a bit for us to implement (due to current circumstances) 

PS: Zipping messages on the fly would be awesome.

Cheers

**Comment by span** [comment]
Awesome. I have not developed for VScode before but I will take a few stabs and see where it ends up.

**Comment by span** [comment]
Here's a first stab at this. I am not 100% happy with the dropdown button but I can't really figure out a cleaner way of doing it at the moment.

Please provide some feedback if you have an opportunity while I will work on some tests.
